1.原理:
  1.jar--->numbus(keepalive)-->supervisor--->worker
  2.序列化（反序列化）---环形队列
  3.spout(数据源)--->bolt
2.使用过程中遇到的问题:
  1.机器不能为纯数字(jstormui)
  2.kill不完全
  3.supervisor假死
3.性能优化:  
  2.控制好每个tuple的大小
  3.做好缓存
  4.业务处理逻辑的优化
  5.数据的聚合和去重
  6.数据倾斜
  7.内存大小设置要合理(型线程数:worker数io密集为1:2，计算密集型为1：1)
  8.设置合理的worker数据量和worker的大小
  9.worker-->进程，bolt--->线程
  10.bolt的分配策略:根据可用端口数分配
  
